### ISSUE TITLE
Laravel 5.2 Driver [vkontakte] not supported

### ISSUE THREAD

**Issue by pavlovskyarto** [SocialiteProviders/VKontakte#8] opened 2016-01-13 09:42 UTC
Hi. I use few socialite providers in my app: facebook, google+ and vkontakte.
Facebook adn G+ woks correctly, but VK doesnt.

InvalidArgumentException in Manager.php line 90: Driver [vkontakte] not supported.

**Comment by AndyWendt** [comment] 2016-01-14 17:14
I have been pushing a lot of changes to the manager class over the last few days.  Maybe try a composer update and make sure it pulls in the latest version (something like 1.2.*).

**Comment by AndyWendt** [comment] 2016-01-17 16:14
No response.  Most likely a user issue or just needed to update

**Comment by pavlovskyarto** [comment] 2016-01-18 11:33
Hi. I cant install version 1.2.* 
composer require socialiteproviders/vkontakte 1.2.*
Result:
The requested package socialiteproviders/vkontakte could not be found in any version, there may be a typo in the package name.

**Comment by AndyWendt** [comment] 2016-01-19 23:28
Version 1.2.x was for the manager package.  This package only has 1.1.2  

Run `composer update` and see if the manager package is updated.

**Comment by pavlovskyarto** [comment] 2016-01-20 08:42
Theres my versions:
socialiteproviders/manager (1.2.3)
socialiteproviders/vkontakte (v1.1.2)

**Comment by pavlovskyarto** [comment] 2016-01-29 14:31
So? Can you fix it?

**Comment by AndyWendt** [comment] 2016-02-05 15:34
@DraperStudio can you look into this?  I don't have a vkontakte account

**Comment by DraperStudio** [comment] 2016-02-05 15:54
@AndyWendt Me neither.

**Comment by AndyWendt** [comment] 2016-02-05 16:21
@DraperStudio this person sent me an email.  He was trying to use google, yandex, facebook, and vkontakte.  I tried the yandex provider and it didn't throw a not supported error so I think he has something wrong with his code: 

```php
        public function redirectToProvider($provider){
            return Socialite::with($provider)->redirect();
        }

        public function handleProviderCallback($provider){
            $user = Socialite::with($provider)->user();

    dd($user);

        }
```

**Comment by DraperStudio** [comment] 2016-02-05 16:48
@AndyWendt Just tried to register and it won't accept my phone number so I can't try it. I used the google and facebook provider a few days ago and had no issues.

**Comment by pavlovskyarto** [comment] 2016-02-12 13:58
@DraperStudio I can create for you test api key from my Vkontakte account.
Contact me please. pavlovsky.art.o@gmail.com

**Comment by DraperStudio** [comment] 2016-02-13 11:50
The account isn't required to be honest. I did a fresh install of Laravel 5.0, 5.1 and 5.2 and the Provider worked with all of them just by following the docs so I don't know what is going wrong.

**Comment by AndyWendt** [comment] 2016-02-14 21:29
I'm not sure what is getting messed up.  Maybe it has something to do with how they are installing Laravel?  I have never been able to reproduce a not supported error.   I'm not quite sure what is failing.  Maybe it has to do with how they are adding the event listeners.   So weird.

**Comment by DraperStudio** [comment] 2016-02-14 21:52
No idea, I can't reproduce them any of them.

They most likely mess up the Event Listener registration since this is the only thing that can cause the not supported message as far as I can see.

**Comment by pavlovskyarto** [comment] 2016-02-16 09:26
There's Laravel 5.2 with only socialite packages installed:
http://laravel-clean.dev.studio-orbita.com.ua/login/vkontakte
Source: https://drive.google.com/file/d/0B7pSWtHeayORN09vdThPX3NiNjg/view?usp=sharing

**Comment by DraperStudio** [comment] 2016-02-16 09:39
You haven't even registered the provider in EventServiceProvider.

**Comment by AndyWendt** [comment] 2016-02-18 02:44
I'm declaring this one user error.  Closing

**Closed by AndyWendt** 2016-02-18 02:44 UTC

**Comment by DraperStudio** [comment] 2016-02-19 09:19
I've created an example of how the basic setup should look like so @pavlovskyarto and other can compare their code with this

https://github.com/SocialiteProviders/Setup-Example

**Comment by AndyWendt** [comment] 2016-02-20 22:15
@DraperStudio Good idea!
